# Generated by Django 4.1.9 on 2023-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kic', models.IntegerField()),
                ('Period', models.FloatField()),
                ('Period_error', models.FloatField()),
                ('bjd0', models.FloatField()),
                ('bjd0_error', models.FloatField()),
                ('Period_td', models.FloatField()),
                ('Period_errortd', models.FloatField()),
                ('e', models.FloatField()),
                ('e_error', models.FloatField()),
                ('a', models.FloatField()),
                ('a_error', models.FloatField()),
                ('omega', models.FloatField()),
                ('omega_error', models.FloatField()),
            ],
        ),
    ]
